name: Validate changes
on:
  pull_request:
    branches: 
      [ develop, 'release/**', 'stage/**', main, master]

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: Terraform fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform install
        uses: hashicorp/setup-terraform@v2

      - name: terraform fmt
        run: |
          cd terraform
          terraform fmt -check -recursive  
        continue-on-error: true
          
  validate:
    runs-on: ubuntu-latest
    name: Terraform validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform install
        uses: hashicorp/setup-terraform@v2

      - name: terraform validate
        run: |
          cd terraform
          terraform init
          terraform validate



#- uses: hashicorp/setup-terraform@v2
#- run: terraform fmt
#- id: fmt
#  run: terraform plan -no-color

#- run: echo ${{ steps.plan.outputs.stdout }}
#- run: echo ${{ steps.plan.outputs.stderr }}
#- run: echo ${{ steps.plan.outputs.exitcode }}  

      
#defaults:
#  run:
#    working-directory: ${{ env.tf_actions_working_dir }}
#permissions:
#  pull-requests: write
#steps:
#- uses: actions/checkout@v3
#- uses: hashicorp/setup-terraform@v2

#- name: Terraform fmt
#  id: fmt
#run: terraform fmt -check
#  continue-on-error: true

#- name: Terraform Init
#  id: init
#  run: terraform init

#- name: Terraform Validate
#  id: validate
# run: terraform validate -no-color
